version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fed-proxy-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3c49fuva84uk"
s3_prefix = "fed-proxy-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StackEnv=\"dev\""

