jobs:
  build_and_deploy_staging:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run: sam build --parameter-overrides StackEnv=dev
      - run: sam deploy --parameter-overrides StackEnv=dev --stack-name=fed-proxy-dev  --confirm-changeset=False
  # build_and_deploy_production:
  #   executor: sam/default
  #   steps:
  #     - checkout
  #     - sam/install
  #     - run: sam build --parameter-overrides StackEnv=dev
  #     - run: sam deploy --parameter-overrides StackEnv=prod --stack-name=fed-proxy-prod  --confirm-changeset=False
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy_staging:
        filters:
          branches:
            only: circleci
      # - build_and_deploy_production:
      #   filters:
      #     branches:
      #       only: master