default-docker-node: &default-docker-node
  image: circleci/node:12
  environment:
    YARN_VERSION: 0.24.6-1

jobs:
  test-stack:
    docker:
       - *default-docker-node
    steps:
      - checkout
      - run:
          name: Display versions
          command: |
            echo $(node --version)
            echo $(yarn --version)
            echo $(npm --version)
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./lambdas/node_modules
            - ~/.cache/yarn
      - run:
          name: Lint changed files
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test

  build_and_deploy_staging:
    executor: aws-serverless/default
    steps:
      - checkout
      - aws-serverless/install:
          aws-access-key-id: AWS_ACCESS_KEY_ID_STAGING
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_STAGING
      - run:
          name: sam build staging
          command: sam build --parameter-overrides StackEnv=staging
      - run:
          name: "sam deploy staging"
          command: sam deploy --parameter-overrides StackEnv=staging --stack-name=federalist-proxy-staging --no-confirm-changeset --no-fail-on-empty-changeset
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - test-stack
      - build_and_deploy_staging:
          requires:
            - test-stack
          filters:
            branches:
              only:
                - main
                - ci-deploy-user