jobs:
  build_and_deploy_staging:
    executor: aws-serverless/default
    steps:
      - checkout
      - aws-serverless/install:
          aws-access-key-id: AWS_ACCESS_KEY_ID_DEV
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_DEV
      - run: sam build --parameter-overrides StackEnv=dev --region us-east-1
      - run: sam deploy --parameter-overrides StackEnv=dev --stack-name=fed-proxy-dev --region us-east-1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy_staging:
        filters:
          branches:
            only: circleci